<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Goodbye Mail</title>
</head>

<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif; margin: 0; padding: 0; background: linear-gradient(to bottom right, #503315, #282c34, #2f1e0c);">
<div style=" align-items: center; max-width: 800px; margin: 0 auto; padding: 20px; color:rgb(249,243,234)">
    <h2 style="text-align: center; margin-top: 20px; color:rgb(249,243,234); line-height: 1;">Hello, </h2>
    <h1 style="text-align: center; margin-top: 10px; color:rgb(249,243,234); line-height: 1;">${name} ${surname}!</h1>
    <div>
        <p style="text-align: center; margin-top: 20px; line-height: 1.5; font-size: 18px;">We're so sorry to say goodbye. Unfortunately, we deleted your account's data. But we're always to see you back! </p>
    </div>
    <div style="text-align: center; margin-top: 100px;">
        <p style="text-align: center; margin-top: 20px; line-height: 1.5;">We wish you success and wait for you!</p>
    </div>
</div>
<footer style="border-top: 1px solid #a1a1a2; padding-top: 20px; color:rgb(249, 243, 234); text-align: center; width: 100%;">
    <p style="line-height: 1.5">ReConstructorCopyright ©</p>
    <p><a href="http://www.reconstructor.me" target="_blank" style="text-decoration: none; color: #c7b492; cursor: pointer;">www.reconstructor.me</a></p>
    <p style="line-height: 1.4; margin: 0 10px;">Mühlenstraße 23, 40213 Düsseldorf, Germany</p>
    <p style="line-height: 1.4; margin: 0 10px;">+49 211 1234567</p>
    <p style="line-height: 1.4; margin: 0 10px; padding-bottom: 40px;"><a href="mailto:we.ratsfamily@gmail.com" style="text-decoration: none; color: #c7b492; cursor: pointer;">RatsFamily@reconstructor.me</a></p>
</footer>
</body>

</html>
