name: Backend package

on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.DEPLOY_SECRET }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'semeru'

      - name: Build with Maven (excluding tests)
        run: mvn -B package --file backend/pom.xml -Dmaven.test.skip=true

      - name: Deploy to main branch
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout --orphan backendBuild
          git rm -rf .
          cp backend/target/*.jar ./
          git add *.jar
          git commit -m "Add generated JAR file"
          git remote add origin_with_token https://$GITHUB_ACTOR:${{ secrets.DEPLOY_SECRET }}@github.com/${{ secrets.REPOSITORY_PATH }}
          git push -u origin_with_token backendBuild --force
